extractors:
  vpk:
    filters:
      - "*_dir.vpk"
processors:
  vtables:
    bin_path: ./bin/vtable_dumper
    filters:
    - "*.dylib"
  strings:
    filters:
    - "*.so"
    - "hl2_osx"
    - "srcds_linux"
  symbols:
    filters:
    - "*.dylib"
    - "hl2_osx"
    - "srcds_linux"
  netvars:
    bin_path: ./bin/nvdumper
    filters:
      - "tf/bin/server_srv.so"
  convars:
    bin_path: ./bin/cvdumper
    filters:
      - "*.so"
  protobufs:
    bin_path: "./bin/ProtobufDumper"
    filters:
      - "*.so"
  bsp:
    filters:
      - "*.bsp"
  vpk:
    filters:
      - "*_dir.vpk"
  copy:
    filters:
      - "*.cfg"
      - "*.txt"
      - "*.res"
      - "*.rc"
      - "*.vdf"
      - "*.pop"
  ice:
    bin_path: "./bin/vice"
    ice_key: "E2NcUkG2"
    filters:
    - "*.ctx"
  # binexport:
  #   filters:
  #     - "*.so"
