[project]
name = "dataminer"
version = "0.1.0"

dependencies = [ "PyYAML" ]

[project.scripts]
dataminer = 'dataminer:run'

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
